site_name: OpenSSL Certificate Authority
site_url: https://zephynyah.github.io/zeph-opensll-certificate-authority/
site_description: A Guide for Creating a certificate authority (CA) using the OpenSSL.
site_author: Zephynyah

repo_url: https://github.com/Zephynyah/zeph-opensll-certificate-authority

nav:
  - Home: index.md
  - About:
    - about/index.md
    - Release Notes: 'about/release-notes.md'
    - Contributing: about/contributing.md
    - License: 'about/license.md'
  - Guides:
    - guides/index.md
    - Create The Root Pair: guides/create-the-root-pair.md
    - Create The Intermediate Pair: guides/create-the-intermediate-pair.md
    - Sign Server and Client Certificates: guides/sign-server-and-client-certificate.md
    - Certificate Revocation Lists: guides/certificate-revocation-lists.md
    - Online Certificate Status Protocol: guides/online-certificate-status-protocol.md
  - Appendix:
    - appendix/index.md
    - Root CA Configuration File: appendix/root-configuration.md
    - Intermediate CA Configuration File: appendix/intermediate-configuration.md
theme:
  name: readthedocs
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
    - navigation.path
    - navigation.indexes
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      # accent: lime

plugins:
  - social
  - search

markdown_extensions:
  - toc:
      title: "ZEPH"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  version: 0.1.0
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

copyright: |
  Copyright &copy; 2023 - 2024 <a href="https://github.com/Zephynyah/"  target="_blank" rel="noopener">Jason Hickey</a>
